modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/ShyNieke/StatuesMod/issues"
license="MIT"

[[mods]]
modId="statues"
version="${file.jarVersion}"
displayName="Statues Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="ShyNieke, Mrbysco"
description='''
Just a little functional decoration.
'''
[[dependencies.statues]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.statues]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.110-beta,)"
ordering="NONE"
side="BOTH"